source 'https://github.com/CocoaPods/Specs.git'

target 'BeanTransitionManager', :exclusive => true do
  pod "BeanTransitionManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BeanTransitionManager", :path => "../"

  
end
